version: "3"

services:
  # Collector
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yml", ""]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      # - '55681:55679' # zpages extension
    depends_on:
      - jaeger

  # BackEnd

  ## Jaeger
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
  # ## Prometheus
  # prometheus:
  #   container_name: prometheus
  #   image: prom/prometheus:v2.43.0
  #   command:
  #     - --config.file=/etc/prometheus/prometheus.yaml # prometheusの設定ファイルの反映
  #   volumes:
  #     - ./prometheus.yaml:/etc/prometheus/prometheus.yaml # 設定ファイルをマウント
  #   ports:
  #     - "9090:9090"

  # ## Grafana
  # grafana:
  #   container_name: grafana
  #   image: grafana/grafana:9.1.0
  #   volumes:
  #     - ./grafana/grafana.ini:/etc/grafana/grafana.ini # grafanaの設定ファイルをマウント
  #     - ./grafana/provisioning/:/etc/grafana/provisioning/ # ダッシュボードとデータソースの設定ファイルをマウント
  #   ports:
  #     - "3000:3000"
